Update skeleton files
nexB/cwe2 pull request #9
Opened 2023-09-28 22:12 UTC by ziadhany

2023-10-01 19:43 UTC, keshav-space requested changes
Thanks @ziadhany ... just a minor nitpick for your consideration.

2023-10-01 19:43 UTC, keshav-space commented on Makefile
> +# See https://github.com/nexB/skeleton for support or download.
```suggestion
# See https://github.com/nexB/cwe2 for support or download.
```

2023-10-03 04:56 UTC, ziadhany commented on Makefile
> +# See https://github.com/nexB/skeleton for support or download.
Done

2023-10-03 08:14 UTC, keshav-space approved these changes
LGTM, thanks ++

2023-10-03 08:15 UTC, merged